# **(EDA NOTEBOOK)**

## Objectives

* Perform Exploratory Data Analysis on the cleaned Telco customer churn dadtaset to understand variable distributions

## Inputs

* Cleaned Telco customer churn dataset - cleaned_telco.csv

## Outputs

* Summary statistics and notes regarding values

## Additional Comments

* These findings will aid feature engineering and modelling steps later in the project.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [2]:
import os
current_dir = os.getcwd()
current_dir

'/Users/isaacola/Documents/vscode-project/Data_Analytics_Capstone/Data-Analytics-Capstone/Research'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [3]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [4]:
current_dir = os.getcwd()
current_dir

'/Users/isaacola/Documents/vscode-project/Data_Analytics_Capstone/Data-Analytics-Capstone'

# Section 1

# Explorative Data Analysis

In [5]:

# Import Libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Load Cleaned Dataset
print("Loading cleaned dataset...")
df = pd.read_csv("../dataset/processed/cleaned_telco.csv")

Loading cleaned dataset...

In [7]:
#  Data Overview
print("First five rows:")
df.head()

First five rows:

,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,...,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,tenure_group
0,Female,0,1,0,1,0,No phone service,DSL,No,Yes,...,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0,0-1yr
1,Male,0,0,0,34,1,No,DSL,Yes,No,...,No,No,No,One year,0,Mailed check,56.95,1889.50,0,2-4yr
2,Male,0,0,0,2,1,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1,0-1yr
3,Male,0,0,0,45,0,No phone service,DSL,Yes,No,...,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,2-4yr
4,Female,0,0,0,2,1,No,Fiber optic,No,No,...,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1,0-1yr

In [8]:
# Display DataFrame info
print("Dataframe info:")
df.info()

Dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7010 entries, 0 to 7009
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7010 non-null   object
 1   seniorcitizen     7010 non-null   int64
 2   partner           7010 non-null   int64
 3   dependents        7010 non-null   int64
 4   tenure            7010 non-null   int64
 5   phoneservice      7010 non-null   int64
 6   multiplelines     7010 non-null   object
 7   internetservice   7010 non-null   object
 8   onlinesecurity    7010 non-null   object
 9   onlinebackup      7010 non-null   object
 10  deviceprotection  7010 non-null   object
 11  techsupport       7010 non-null   object
 12  streamingtv       7010 non-null   object
 13  streamingmovies   7010 non-null   object
 14  contract          7010 non-null   object
 15  paperlessbilling  7010 non-null   int64
 16  paymentmethod     7010 non-null   object
 17  monthlycharges    7010 non-null   float64
 18  totalcharges      7010 non-null   float64
 19  churn             7010 non-null   int64
 20  tenure_group      7010 non-null   object
dtypes: float64(2), int64(7), object(12)
memory usage: 1.1+ MB

In [9]:
# Statistical summary
df.describe(include="all")

,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,...,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn,tenure_group
count,7010,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010,7010,7010,7010,...,7010,7010,7010,7010,7010.000000,7010,7010.000000,7010.000000,7010.000000,7010
unique,2,NaN,NaN,NaN,NaN,NaN,3,3,3,3,...,3,3,3,3,NaN,4,NaN,NaN,NaN,5
top,Male,NaN,NaN,NaN,NaN,NaN,No,Fiber optic,No,No,...,No,No,No,Month-to-month,NaN,Electronic check,NaN,NaN,NaN,0-1yr
freq,3535,NaN,NaN,NaN,NaN,NaN,3363,3090,3489,3079,...,3464,2801,2773,3853,NaN,2359,NaN,NaN,NaN,2153
mean,NaN,0.162767,0.484023,0.299429,32.520399,0.902996,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.593153,NaN,64.888666,2290.353388,0.264907,NaN
std,NaN,0.369180,0.499780,0.458041,24.520441,0.295985,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.491281,NaN,30.064769,2266.820832,0.441315,NaN
min,NaN,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,18.250000,18.800000,0.000000,NaN
25%,NaN,0.000000,0.000000,0.000000,9.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,35.750000,408.312500,0.000000,NaN
50%,NaN,0.000000,0.000000,0.000000,29.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,70.400000,1403.875000,0.000000,NaN
75%,NaN,0.000000,1.000000,1.000000,56.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,89.900000,3807.837500,1.000000,NaN
max,NaN,1.000000,1.000000,1.000000,72.000000,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,118.750000,8684.800000,1.000000,NaN

In [10]:
# Check target variable distribution
df["churn"].value_counts()

churn
0    5153
1    1857
Name: count, dtype: int64

---